# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module DateTimeOptionalTest
  # unix time stamp exception class.
  class UnixTimeStampException < APIException
    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :date_time

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :date_time_1

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpContext] The HttpContext of the API call.
    def initialize(reason, context)
      super(reason, context)
      hash = APIHelper.json_deserialize(@context.response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @date_time = Time.at(hash['dateTime']).utc.to_datetime if
        hash['dateTime']
      @date_time_1 = Time.at(hash['dateTime1']).utc.to_datetime if
        hash['dateTime1']
    end
  end
end
