# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

require_relative 'controller_test_base'

class FormParamsControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.form_params
  end

  # Todo: Add description for test test_send_optional_unix_time_stamp_in_model_body
  def test_send_optional_unix_time_stamp_in_model_body()
    # Parameters for the API call
    date_time = UnixDateTime.from_hash(JSON.parse('{"dateTime":1484719381}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_optional_unix_time_stamp_in_model_body(date_time)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_test_sending_datetime_as_optional_in_plain_text_body
  def test_test_sending_datetime_as_optional_in_plain_text_body()
    # Parameters for the API call
    body = DateTime.rfc3339('1994-02-13T14:01:54.9571247Z')

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_datetime_optional_in_endpoint(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_optional_rfc_1123_in_body
  def test_send_optional_rfc_1123_in_body()
    # Parameters for the API call
    body = DateTime.httpdate('Sun, 06 Nov 1994 08:49:37 GMT')

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_optional_rfc_1123_in_body(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_optional_unix_time_stamp_in_body
  def test_send_optional_unix_time_stamp_in_body()
    # Parameters for the API call
    date_time = Time.at(1484719381).utc.to_datetime

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_optional_unix_date_time_in_body(date_time)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_rfc_3339_date_time_in_nested_model
  def test_send_rfc_3339_date_time_in_nested_model()
    # Parameters for the API call
    body = SendRfc339DateTime.from_hash(JSON.parse('{"dateTime":{"dateTime":"1994-02-13T14:01:54.9571247Z"}}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_rfc_339_date_time_in_nested_models(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_optional_datetime_in_model_as_body
  def test_send_optional_datetime_in_model_as_body()
    # Parameters for the API call
    body = ModelWithOptionalRfc3339DateTime.from_hash(JSON.parse('{"dateTime":"1994-02-13T14:01:54.9571247Z"}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_optional_datetime_in_model(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_optional_rfc_1123_date_time_in_model_body
  def test_send_optional_rfc_1123_date_time_in_model_body()
    # Parameters for the API call
    date_time = ModelWithOptionalRfc1123DateTime.from_hash(JSON.parse('{"dateTime":"Sun, 06 Nov 1994 08:49:37 GMT"}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_rfc_1123_date_time_in_model(date_time)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_test_sending_rfc_1123_date_time_in_nested_mode
  def test_test_sending_rfc_1123_date_time_in_nested_mode()
    # Parameters for the API call
    body = SendRfc1123DateTime.from_hash(JSON.parse('{"dateTime":{"dateTime":"Sun, 06 Nov 1994 08:49:37 GMT"}}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_rfc_1123_date_time_in_nested_model(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_send_optional_unix_time_stamp_in_nested_model_body
  def test_send_optional_unix_time_stamp_in_nested_model_body()
    # Parameters for the API call
    date_time = SendUnixDateTime.from_hash(JSON.parse('{"dateTime":{"dateTime":1484719381}}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_optional_unix_time_stamp_in_nested_model_body(date_time)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_uuid_as_optional
  def test_uuid_as_optional()
    # Parameters for the API call
    body = UuidAsOptional.from_hash(JSON.parse('{"uuid":"123e4567-e89b-12d3-a456-426655440000"}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_uuid_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_boolean_as_optional
  def test_boolean_as_optional()
    # Parameters for the API call
    body = BooleanAsOptional.from_hash(JSON.parse('{"boolean":true}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_boolean_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_date_as_optional
  def test_date_as_optional()
    # Parameters for the API call
    body = DateAsOptional.from_hash(JSON.parse('{"date":"1994-02-13"}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_date_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_dynamic_as_optional
  def test_dynamic_as_optional()
    # Parameters for the API call
    body = DynamicAsOptional.from_hash(JSON.parse('{"dynamic":{"dynamic":"test"}}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_dynamic_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_string_as_optional
  def test_string_as_optional()
    # Parameters for the API call
    body = StringAsOptional.from_hash(JSON.parse('{"string":"test"}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_string_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_precision_as_optional
  def test_precision_as_optional()
    # Parameters for the API call
    body = PrecisionAsOptional.from_hash(JSON.parse('{"precision":1.23}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_precision_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_long_as_optional
  def test_long_as_optional()
    # Parameters for the API call
    body = LongAsOptional.from_hash(JSON.parse('{"long":123123}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_long_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

  # Todo: Add description for test test_number_as_optional
  def test_number_as_optional()
    # Parameters for the API call
    body = NumberAsOptional.from_hash(JSON.parse('{"number":1}'))

    # Perform the API call through the SDK function
    result = self.class.controller.create_send_number_as_optional(body)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    expected_body = JSON.parse('{"passed":true}')
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

end
