# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # BooleanAsOptional Model.
  class BooleanAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :boolean

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['boolean'] = 'boolean'
      @_hash
    end

    def initialize(boolean = nil)
      @boolean = boolean
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      boolean = hash['boolean']

      # Create object from extracted values.
      BooleanAsOptional.new(boolean)
    end
  end
end
