# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # DateAsOptional Model.
  class DateAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [Date]
    attr_accessor :date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['date'] = 'date'
      @_hash
    end

    def initialize(date = nil)
      @date = date
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      date = hash['date']

      # Create object from extracted values.
      DateAsOptional.new(date)
    end
  end
end
