# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # DynamicAsOptional Model.
  class DynamicAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :dynamic

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['dynamic'] = 'dynamic'
      @_hash
    end

    def initialize(dynamic = nil)
      @dynamic = dynamic
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      dynamic = hash['dynamic']

      # Create object from extracted values.
      DynamicAsOptional.new(dynamic)
    end
  end
end
