# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # LongAsOptional Model.
  class LongAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [Long]
    attr_accessor :long

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['long'] = 'long'
      @_hash
    end

    def initialize(long = nil)
      @long = long
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      long = hash['long']

      # Create object from extracted values.
      LongAsOptional.new(long)
    end
  end
end
