# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # StringAsOptional Model.
  class StringAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :string

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['string'] = 'string'
      @_hash
    end

    def initialize(string = nil)
      @string = string
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      string = hash['string']

      # Create object from extracted values.
      StringAsOptional.new(string)
    end
  end
end
