# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  # UuidAsOptional Model.
  class UuidAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [UUID | String]
    attr_accessor :uuid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['uuid'] = 'uuid'
      @_hash
    end

    def initialize(uuid = nil)
      @uuid = uuid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      uuid = hash['uuid']

      # Create object from extracted values.
      UuidAsOptional.new(uuid)
    end
  end
end
